version: '3.0'
services:
  backend:
    build: 
      context: .
      dockerfile: dockerfile
    restart : unless-stopped
    ports:
      - 8000:8000
    environment:
      PORT : 8000
      URL_DATABASE : "mongodb+srv://root:root@cluster0.nbqvme4.mongodb.net/"
      PRIVATE_KEY : "PHANKIEN11032002"
      PRIVATE_RESET_KEY : "PHANKIEN11032002reset"